# Generated by Django 4.0.8 on 2024-04-03 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_delete_activecourseregistrationrecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exam.customer'),
            preserve_default=False,
        ),
    ]
