# Generated by Django 4.0.8 on 2024-04-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_rename_role_id_user_role_role_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitylog',
            table='activity_log',
        ),
        migrations.AlterModelTable(
            name='choice',
            table='choice',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='courseenrollment',
            table='course_enrollment',
        ),
        migrations.AlterModelTable(
            name='courseregisterrecord',
            table='course_registration_record',
        ),
        migrations.AlterModelTable(
            name='coursestructure',
            table='course_structure',
        ),
        migrations.AlterModelTable(
            name='progress',
            table='progress',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quiz',
        ),
        migrations.AlterModelTable(
            name='quizattempthistory',
            table='quiz_attempt_history',
        ),
        migrations.AlterModelTable(
            name='uploadreadingmaterial',
            table='upload_reading_material',
        ),
        migrations.AlterModelTable(
            name='uploadvideo',
            table='upload_video',
        ),
    ]
