# Generated by Django 4.0.8 on 2024-04-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_activitylog_table_alter_choice_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerresources',
            options={'verbose_name_plural': 'Customer Resources'},
        ),
        migrations.AlterModelOptions(
            name='resources',
            options={'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='userroleprivileges',
            options={'verbose_name_plural': 'User Role Privileges'},
        ),
        migrations.AlterModelTable(
            name='customerresources',
            table='customer_resources',
        ),
        migrations.AlterModelTable(
            name='resources',
            table='resources',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='userroleprivileges',
            table='user_role_privileges',
        ),
    ]
