# Generated by Django 4.0.8 on 2024-04-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_question_created_at_question_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregisterrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseregisterrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
