# Generated by Django 4.0.8 on 2024-04-05 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_courseregisterrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestructure',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursestructure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursestructure',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coursestructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
