# Generated by Django 4.0.8 on 2024-04-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_coursestructure_active_coursestructure_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursestructure',
            options={},
        ),
        migrations.AddField(
            model_name='uploadreadingmaterial',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
