# Generated by Django 5.0.1 on 2024-04-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_quizscore_coursecompletionstatusperuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
