# Generated by Django 5.0.1 on 2024-04-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_remove_customer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_resources',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customerresources',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='customer_resources',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='status',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='user_role_privileges',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userroleprivileges',
            name='has_read',
        ),
        migrations.RemoveField(
            model_name='userroleprivileges',
            name='has_write',
        ),
        migrations.RemoveField(
            model_name='userroleprivileges',
            name='role',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
