# Generated by Django 5.0.1 on 2024-04-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_remove_choice_active_remove_choice_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
